version: 1.2
workflows:
   - name: STAR-Fusion-WDL-hg38v22
     subclass: WDL
     primaryDescriptorPath: /star_fusion_hg38_wf.wdl
     authors:
         - name: Brian Haas
           email: bhaas@broadinstitute.org
	 - name: Amy Olex
	   email: alolex@vcu.edu
