include required(classpath("application"))

backend {
  default = "SLURM"
  providers {
    SLURM {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
          Int cpu = 12
          String memory = "100G"
          String? docker
          String? slurm_partition = "YOUR_PARTITION"
          String? time_limit = "24:00:00"
        """

        submit = """
          sbatch \
            --job-name=${job_name} \
            --partition=${slurm_partition} \
            --cpus-per-task=${cpu} \
            --mem=${memory} \
            --time=${time_limit} \
            --output=${cwd}/execution/main_stdout \
            --error=${cwd}/execution/main_stderr \
            /bin/bash ${script}
        """

        submit-docker = """
          echo '#!/bin/bash
          module load YOUR_SINGULARITY_MODULE
          singularity exec --bind ${cwd}:${docker_cwd} --bind YOUR_BASE_DATA_PATH:YOUR_BASE_DATA_PATH docker://${docker} ${job_shell} ${docker_script}' > ${cwd}/execution/submit_script.sh
          chmod 755 ${cwd}/execution/submit_script.sh
          sbatch \
            --job-name=${job_name} \
            --partition=${slurm_partition} \
            --cpus-per-task=${cpu} \
            --mem=${memory} \
            --time=${time_limit} \
            --output=${cwd}/execution/docker_stdout \
            --error=${cwd}/execution/docker_stderr \
            ${cwd}/execution/submit_script.sh
        """

        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "(\\d+)"

        root = "cromwell-executions"

        # Use symlinks instead of copying input files to save disk space
        filesystems {
          local {
            localization = [ "soft-link", "copy" ]
          }
        }
      }
    }
  }
}
